#!/usr/bin/python3

from util       import run_cmd, capture,syshost
import allocations as alloc
import allocations3 as alloc3
from datetime import *
import re, sys
print("ORIG ALLOCATIONS:")
alloc.allocations()
print()
print("ALLOCATIONS3:")
alloc3.allocations()
